# Generated by Django 4.2.2 on 2023-06-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={},
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='campus_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='campus_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
